### ISSUE TITLE
Add support for Linux

### ISSUE THREAD

**Issue by lauriii** [druidfi/druid-toolbelt#6]
There is already Druid's running Linux on their devices, and most likely in the future, there will be more. It would be useful if this tool would be somewhat usable also for Linux users. It could also lower the barrier of moving from Mac OSX to Linux.

**Comment by back-2-95** [comment]
We could have another script here for Linux? So "if using Linux please use this command".
No point to make the same script work for both as OSX one is heavily dependant on Homebrew.

**Comment by lauriii** [comment]
Technically it is easy to test if homebrew / apt / yum exists or test even the OS family to figure that out. That would be the same way ansible works. So technically there is no limitations for this. Only limitation is that it is not currently supported.

**Comment by back-2-95** [comment]
Won't fix.
